global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'slack.critical'
    continue: true
  - match:
      severity: warning
    receiver: 'slack.warning'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'slack.critical'
  slack_configs:
  - channel: '#alerts-critical'
    title: '{{ template "slack.title" . }}'
    text: '{{ template "slack.text" . }}'
    color: 'danger'
    send_resolved: true

- name: 'slack.warning'
  slack_configs:
  - channel: '#alerts-warning'
    title: '{{ template "slack.title" . }}'
    text: '{{ template "slack.text" . }}'
    color: 'warning'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

templates:
- '/etc/alertmanager/template/*.tmpl'
